#!/usr/bin/env python3
"""
Автоматическая сборка GibVPN_Smart_v3.exe.

Что делает:
  1. Убивает запущенные копии GibVPN_Smart_v3.exe (чтобы не было блокировки файла).
  2. Запускает no-xray тесты.
  3. Пересобирает exe через PyInstaller.
  4. Запускает тесты ещё раз после сборки.
  5. Обновляет gui_preview.png и settings_preview.png из скриншотов.

Использование:
  python build.py
"""
import os
import subprocess
import sys
import shutil
import glob

WORK_DIR = os.path.dirname(os.path.abspath(__file__))
EXE_NAME = "GibVPN_Smart_v3.exe"
DIST_EXE = os.path.join(WORK_DIR, "dist", "GibVPN_Smart_v3", EXE_NAME)


def run(cmd, **kwargs):
    print(f"\n>>> {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=WORK_DIR, text=True, **kwargs)
    return result


def kill_running_exe():
    print("Killing running instances of the app...")
    if sys.platform == "win32":
        subprocess.run(
            ["taskkill", "/F", "/IM", EXE_NAME],
            capture_output=True,
            shell=False,
        )
    else:
        subprocess.run(
            ["pkill", "-f", EXE_NAME],
            capture_output=True,
        )


def run_tests():
    env = os.environ.copy()
    env["QT_QPA_PLATFORM"] = "offscreen"
    result = run(
        [sys.executable, "tests/test_no_xray.py", "-v"],
        env=env,
    )
    if result.returncode != 0:
        print("TESTS FAILED. Aborting build.")
        sys.exit(1)
    print("Tests passed.")


def build_exe():
    # Remove old dist exe if locked
    if os.path.exists(DIST_EXE):
        try:
            os.remove(DIST_EXE)
        except OSError:
            print("Could not remove old exe, trying to kill process again...")
            kill_running_exe()
            os.remove(DIST_EXE)

    result = run(
        [sys.executable, "-m", "PyInstaller", "GibVPN_Smart_v3.spec", "--noconfirm", "--clean"],
    )
    if result.returncode != 0:
        print("PyInstaller build failed.")
        sys.exit(1)

    if not os.path.exists(DIST_EXE):
        print(f"Built exe not found at {DIST_EXE}")
        sys.exit(1)

    print(f"Build complete: {DIST_EXE}")


def update_previews():
    # Live previews are generated by test_no_xray.py during build
    if os.path.exists(os.path.join(WORK_DIR, "gui_preview.png")):
        print("Live gui_preview.png verified.")
    if os.path.exists(os.path.join(WORK_DIR, "settings_preview.png")):
        print("Live settings_preview.png verified.")


def main():
    os.chdir(WORK_DIR)
    kill_running_exe()
    run_tests()
    build_exe()
    run_tests()
    update_previews()
    print("\n=== BUILD SUCCESS ===")
    print(f"Output: {DIST_EXE}")


if __name__ == "__main__":
    main()
