#!/usr/bin/env python3
"""
Автоматическая сборка GibVPN_Smart_v3.exe.

Что делает:
  1. Убивает запущенные копии GibVPN_Smart_v3.exe (чтобы не было блокировки файла).
  2. Запускает no-xray тесты.
  3. Пересобирает exe через PyInstaller.
  4. Запускает тесты ещё раз после сборки.
  5. Обновляет gui_preview.png и settings_preview.png из скриншотов.

Использование:
  python build.py
"""
import os
import subprocess
import sys
import shutil
import glob
import hashlib
import tempfile
import urllib.request
import zipfile

WORK_DIR = os.path.dirname(os.path.abspath(__file__))
EXE_NAME = "GibVPN_Smart_v3.exe"
DIST_EXE = os.path.join(WORK_DIR, "dist", EXE_NAME)
XRAY_VERSION = "26.7.28"
XRAY_ARCHIVE_SHA256 = "c7172078fca4711bcd92a4774dcd1822544579c58816197575c47533317fd8d1"
XRAY_URL = (
    f"https://github.com/XTLS/Xray-core/releases/download/v{XRAY_VERSION}/"
    "Xray-windows-64.zip"
)


def run(cmd, **kwargs):
    print(f"\n>>> {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=WORK_DIR, text=True, **kwargs)
    return result


def kill_running_exe():
    print("Killing running instances of the app...")
    if sys.platform == "win32":
        subprocess.run(
            ["taskkill", "/F", "/IM", EXE_NAME],
            capture_output=True,
            shell=False,
        )
    else:
        subprocess.run(
            ["pkill", "-f", EXE_NAME],
            capture_output=True,
        )


def ensure_xray():
    """Download the pinned official Xray build and verify its release hash."""
    xray_path = os.path.join(WORK_DIR, "xray.exe")
    if os.path.exists(xray_path):
        version = subprocess.run(
            [xray_path, "version"], capture_output=True, text=True
        )
        if version.returncode == 0 and f"Xray {XRAY_VERSION} " in version.stdout:
            print(f"Xray {XRAY_VERSION} verified.")
            return

    print(f"Downloading official Xray {XRAY_VERSION}...")
    with tempfile.TemporaryDirectory(prefix="gibvpn_xray_") as tmp:
        archive_path = os.path.join(tmp, "Xray-windows-64.zip")
        request = urllib.request.Request(
            XRAY_URL, headers={"User-Agent": "GibVPN-Builder/3.0"}
        )
        with urllib.request.urlopen(request, timeout=60) as response:
            with open(archive_path, "wb") as target:
                shutil.copyfileobj(response, target)

        digest = hashlib.sha256()
        with open(archive_path, "rb") as source:
            for chunk in iter(lambda: source.read(1024 * 1024), b""):
                digest.update(chunk)
        if digest.hexdigest() != XRAY_ARCHIVE_SHA256:
            raise RuntimeError("Xray archive SHA-256 mismatch")

        with zipfile.ZipFile(archive_path) as archive:
            for name in ("xray.exe", "geoip.dat", "geosite.dat"):
                temp_target = os.path.join(WORK_DIR, name + ".new")
                with archive.open(name) as source, open(temp_target, "wb") as target:
                    shutil.copyfileobj(source, target)
                os.replace(temp_target, os.path.join(WORK_DIR, name))

    version = subprocess.run([xray_path, "version"], capture_output=True, text=True)
    if version.returncode != 0 or f"Xray {XRAY_VERSION} " not in version.stdout:
        raise RuntimeError("Downloaded Xray version verification failed")
    print(f"Xray {XRAY_VERSION} installed and hash-verified.")


def run_tests():
    env = os.environ.copy()
    env["QT_QPA_PLATFORM"] = "offscreen"
    result = run(
        [sys.executable, "tests/test_no_xray.py", "-v"],
        env=env,
    )
    if result.returncode != 0:
        print("TESTS FAILED. Aborting build.")
        sys.exit(1)
    print("Tests passed.")


def build_exe():
    # Remove old dist exe if locked
    if os.path.exists(DIST_EXE):
        try:
            os.remove(DIST_EXE)
        except OSError:
            try:
                temp_old = DIST_EXE + ".old"
                if os.path.exists(temp_old):
                    try:
                        os.remove(temp_old)
                    except OSError:
                        pass
                os.replace(DIST_EXE, temp_old)
                print(f"Renamed locked {DIST_EXE} to {temp_old}")
            except OSError:
                kill_running_exe()

    result = run(
        [sys.executable, "-m", "PyInstaller", "GibVPN_Smart_v3.spec", "--noconfirm", "--clean"],
    )
    if result.returncode != 0:
        print("PyInstaller build failed.")
        sys.exit(1)

    if not os.path.exists(DIST_EXE):
        print(f"Built exe not found at {DIST_EXE}")
        sys.exit(1)

    print(f"Build complete: {DIST_EXE}")


def update_previews():
    # Live previews are generated by test_no_xray.py during build
    if os.path.exists(os.path.join(WORK_DIR, "gui_preview.png")):
        print("Live gui_preview.png verified.")
    if os.path.exists(os.path.join(WORK_DIR, "settings_preview.png")):
        print("Live settings_preview.png verified.")


def main():
    os.chdir(WORK_DIR)
    kill_running_exe()
    ensure_xray()
    run_tests()
    build_exe()
    run_tests()
    update_previews()
    print("\n=== BUILD SUCCESS ===")
    print(f"Output: {DIST_EXE}")


if __name__ == "__main__":
    main()
